development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_BRONZE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: screwapp_production
